dotenv: .env

networks:
  default: development
  development:
    cmd_settings:
      mnemonic: bla
      default_balance: 100
      # unlock: <ACCOUNT ADDRESS HERE> # optionally add saved brownie account to Ganache
      # # (requires explicit transfer of eth to accounts[-1]) 

    update_interval: 60
    verify: False

compiler:
  solc:
    version: 0.5.16
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.0
  